/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/resumes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Upload Resume */
        post: operations["upload_resume_api_v1_resumes_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/resumes/{resume_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Resume */
        get: operations["get_resume_api_v1_resumes__resume_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/resumes/{resume_id}/matches": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Resume Matches */
        get: operations["list_resume_matches_api_v1_resumes__resume_id__matches_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/resumes/{resume_id}/recommendations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Get Recommendations
         * @description Phase 12. Requires an already-computed Match for (resume_id,
         *     job_id) — POST /matches first — never scores on the fly here, so the
         *     score is always already committed before any LLM call happens.
         */
        post: operations["get_recommendations_api_v1_resumes__resume_id__recommendations_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/jobs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Job */
        post: operations["create_job_api_v1_jobs_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/jobs/{job_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Job */
        get: operations["get_job_api_v1_jobs__job_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/matches": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Match */
        post: operations["create_match_api_v1_matches_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/matches/{match_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Match */
        get: operations["get_match_api_v1_matches__match_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/skills/taxonomy": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Browse Taxonomy */
        get: operations["browse_taxonomy_api_v1_skills_taxonomy_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health
         * @description Liveness/readiness check: confirms the app is up and the DB is reachable.
         */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** Body_create_job_api_v1_jobs_post */
        Body_create_job_api_v1_jobs_post: {
            /** Raw Text */
            raw_text?: string | null;
            /** Title */
            title?: string | null;
            /** Company */
            company?: string | null;
            /** File */
            file?: string | null;
        };
        /** Body_upload_resume_api_v1_resumes_post */
        Body_upload_resume_api_v1_resumes_post: {
            /** File */
            file: string;
        };
        /** CandidateProfile */
        CandidateProfile: {
            contact: components["schemas"]["ContactInfo"];
            /** Summary */
            summary?: string | null;
            /**
             * Skills
             * @default []
             */
            skills: string[];
            /**
             * Experience
             * @default []
             */
            experience: components["schemas"]["ExperienceEntry"][];
            /**
             * Projects
             * @default []
             */
            projects: components["schemas"]["ProjectEntry"][];
            /**
             * Education
             * @default []
             */
            education: components["schemas"]["EducationEntry"][];
            /**
             * Certifications
             * @default []
             */
            certifications: string[];
        };
        /** ContactInfo */
        ContactInfo: {
            /** Name */
            name?: string | null;
            /** Email */
            email?: string | null;
            /** Phone */
            phone?: string | null;
            /** Location */
            location?: string | null;
            /**
             * Links
             * @default []
             */
            links: string[];
        };
        /** EducationEntry */
        EducationEntry: {
            /** Degree */
            degree?: string | null;
            /** Field Of Study */
            field_of_study?: string | null;
            /** Institution */
            institution?: string | null;
            /** Graduation Year */
            graduation_year?: string | null;
        };
        /** EvidencedClaimResponse */
        EvidencedClaimResponse: {
            /** Text */
            text: string;
            /** Evidence Ref */
            evidence_ref: string | null;
            /** Is Inference */
            is_inference: boolean;
            /** Evidence Text */
            evidence_text: string | null;
        };
        /** ExperienceEntry */
        ExperienceEntry: {
            /** Title */
            title?: string | null;
            /** Organization */
            organization?: string | null;
            /** Start Date */
            start_date?: string | null;
            /** End Date */
            end_date?: string | null;
            /**
             * Bullets
             * @default []
             */
            bullets: string[];
        };
        /** FeatureVector */
        FeatureVector: {
            /** Required Skill Coverage */
            required_skill_coverage: number;
            /** Preferred Skill Coverage */
            preferred_skill_coverage: number;
            /** Semantic Experience Similarity */
            semantic_experience_similarity: number;
            /** Project Relevance Similarity */
            project_relevance_similarity: number;
            /** Education Match */
            education_match: number;
            /** Years Experience Match */
            years_experience_match: number;
            /** Domain Similarity */
            domain_similarity: number;
            /** Responsibility Similarity */
            responsibility_similarity: number;
            /** Seniority Match */
            seniority_match: number;
            /** Skill Importance Weighted Score */
            skill_importance_weighted_score: number;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** JobProfile */
        JobProfile: {
            /** Title */
            title?: string | null;
            /** @default unspecified */
            seniority: components["schemas"]["SeniorityLevel"];
            /**
             * Requirements
             * @default []
             */
            requirements: components["schemas"]["RequirementItem"][];
            /**
             * Responsibilities
             * @default []
             */
            responsibilities: string[];
            /** About */
            about?: string | null;
        };
        /** JobResponse */
        JobResponse: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Title */
            title: string | null;
            /** Company */
            company: string | null;
            /** Source */
            source: string;
            parsed_profile: components["schemas"]["JobProfile"];
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** MatchCreateRequest */
        MatchCreateRequest: {
            /**
             * Resume Id
             * Format: uuid
             */
            resume_id: string;
            /**
             * Job Id
             * Format: uuid
             */
            job_id: string;
        };
        /** MatchExplanationResponse */
        MatchExplanationResponse: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Match Id
             * Format: uuid
             */
            match_id: string;
            /** Matching Skills */
            matching_skills: string[];
            /** Missing Skills */
            missing_skills: string[];
            /** Partial Skills */
            partial_skills: string[];
            /** Strengths */
            strengths: components["schemas"]["EvidencedClaimResponse"][];
            /** Weaknesses */
            weaknesses: components["schemas"]["EvidencedClaimResponse"][];
            /** Recommendations */
            recommendations: components["schemas"]["RecommendationResponse"][];
            /** Narrative */
            narrative: string | null;
            /** Llm Model */
            llm_model: string | null;
            /** Evidence Check Passed */
            evidence_check_passed: boolean;
            /**
             * Generated At
             * Format: date-time
             */
            generated_at: string;
        };
        /** MatchResponse */
        MatchResponse: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Resume Id
             * Format: uuid
             */
            resume_id: string;
            /**
             * Job Id
             * Format: uuid
             */
            job_id: string;
            feature_vector: components["schemas"]["FeatureVector"];
            skill_breakdown: components["schemas"]["SkillBreakdown"];
            /** Rule Based Score */
            rule_based_score: number;
            /** Ml Score */
            ml_score: number | null;
            /** Scoring Model Version */
            scoring_model_version: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** ProjectEntry */
        ProjectEntry: {
            /** Name */
            name?: string | null;
            /**
             * Bullets
             * @default []
             */
            bullets: string[];
        };
        /** RecommendationResponse */
        RecommendationResponse: {
            /** Suggestion */
            suggestion: string;
            /** Based On */
            based_on: string;
            /** Fabricated Metric */
            fabricated_metric: boolean;
            /** Evidence Text */
            evidence_text: string | null;
        };
        /** RequirementItem */
        RequirementItem: {
            /** Text */
            text: string;
            level: components["schemas"]["RequirementLevel"];
            /**
             * Skills
             * @default []
             */
            skills: string[];
        };
        /**
         * RequirementLevel
         * @enum {string}
         */
        RequirementLevel: "required" | "preferred";
        /** ResumeResponse */
        ResumeResponse: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Original Filename */
            original_filename: string;
            /** File Type */
            file_type: string;
            parsed_profile: components["schemas"]["CandidateProfile"];
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /**
         * SeniorityLevel
         * @enum {string}
         */
        SeniorityLevel: "unspecified" | "junior" | "mid" | "senior" | "staff";
        /**
         * SkillBreakdown
         * @description Named-skill counterpart to required_skill_coverage/preferred_skill_coverage
         *     (Phase 9) — those are aggregate fractions in FeatureVector; the frontend's
         *     matching/missing skill chips (docs/ARCHITECTURE.md §11) need the actual
         *     canonical skill names, taxonomy-normalized the same way the coverage
         *     numbers are, not a naive client-side string comparison.
         */
        SkillBreakdown: {
            /** Matched Required */
            matched_required: string[];
            /** Missing Required */
            missing_required: string[];
            /** Matched Preferred */
            matched_preferred: string[];
            /** Missing Preferred */
            missing_preferred: string[];
        };
        /** SkillTaxonomyEntry */
        SkillTaxonomyEntry: {
            /** Canonical Name */
            canonical_name: string;
            /** Category */
            category: string;
            /** Source */
            source: string;
            /** Aliases */
            aliases: string[];
        };
        /** SkillTaxonomyResponse */
        SkillTaxonomyResponse: {
            /** Skills */
            skills: components["schemas"]["SkillTaxonomyEntry"][];
            /** Total */
            total: number;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    upload_resume_api_v1_resumes_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_upload_resume_api_v1_resumes_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResumeResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_resume_api_v1_resumes__resume_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                resume_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResumeResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_resume_matches_api_v1_resumes__resume_id__matches_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                resume_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MatchResponse"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_recommendations_api_v1_resumes__resume_id__recommendations_post: {
        parameters: {
            query: {
                job_id: string;
            };
            header?: never;
            path: {
                resume_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MatchExplanationResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_job_api_v1_jobs_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "multipart/form-data": components["schemas"]["Body_create_job_api_v1_jobs_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_job_api_v1_jobs__job_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_match_api_v1_matches_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MatchCreateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MatchResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_match_api_v1_matches__match_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                match_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MatchResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    browse_taxonomy_api_v1_skills_taxonomy_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SkillTaxonomyResponse"];
                };
            };
        };
    };
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
}
